## IMPORTAÇÃO DE LIBS

In [ ]:
import pandas as pd

### ANÁLISE EXPLORATÓRIA

In [ ]:
dados = pd.read_csv('/content/SAMPLE_ENERGY_DATA.csv')

In [ ]:
type(dados)

pandas.core.frame.DataFrame

In [ ]:
# Visualizar os primeiros registros
dados.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2008-12-01 00:00:00,2026-08-07 09:44:00,1.502,0.074,240.17,6.4,0,0,18
1,2006-12-17 00:00:00,2026-08-07 23:39:00,0.374,0.264,245.50,1.8,0,2,0
2,2009-06-03 00:00:00,2026-08-07 17:01:00,0.620,0.300,239.85,3.0,0,1,1
3,2007-05-09 00:00:00,2026-08-07 05:53:00,0.280,0.200,235.72,1.4,0,0,0
4,2008-12-14 00:00:00,2026-08-07 02:57:00,1.372,0.054,243.95,5.6,0,0,18

In [ ]:
# Dimensões do Pandas Data Frame
dados.shape

(163943, 9)

In [ ]:
print(f'Total de registros (linhas): {dados.shape[0]}')

Total de registros (linhas): 163943

In [ ]:
# Informações dos atributos (formato dos dados)
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163943 entries, 0 to 163942
Data columns (total 9 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Date                   163943 non-null  object
 1   Time                   163943 non-null  object
 2   Global_active_power    163943 non-null  float64
 3   Global_reactive_power  163943 non-null  float64
 4   Voltage                163943 non-null  float64
 5   Global_intensity       163943 non-null  float64
 6   Sub_metering_1         163943 non-null  int64
 7   Sub_metering_2         163943 non-null  int64
 8   Sub_metering_3         163943 non-null  int64
dtypes: float64(4), int64(3), object(2)
memory usage: 11.3+ MB

In [ ]:
# Estatísticas descritivas dos atributos numéricos
# min, max, media, mediana, desvio padrao, distribuição dos quartis e contagem
dados.describe()

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
count,163943.000000,163943.000000,163943.000000,163943.000000,163943.000000,163943.000000,163943.000000
mean,1.093051,0.124073,240.827630,4.633563,1.134236,1.315286,6.480124
std,1.062535,0.112305,3.242136,4.465014,6.202420,5.891517,8.454072
min,0.076000,0.000000,224.870000,0.200000,0.000000,0.000000,0.000000
25%,0.308000,0.048000,238.980000,1.400000,0.000000,0.000000,0.000000
50%,0.600000,0.100000,241.000000,2.600000,0.000000,0.000000,1.000000
75%,1.526000,0.196000,242.880000,6.400000,0.000000,1.000000,17.000000
max,10.290000,1.078000,253.750000,44.600000,83.000000,79.000000,31.000000

In [ ]:
# itens ===> pares chave-valor
dict1 = {
  'chave1': 'valor1',
  'chave2': 'valor2',
  'chave3': 'valor3'
}

In [ ]:
dict1['chave1']

'valor1'

In [ ]:
dados.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')

In [ ]:
# Renomear todos os rótulos do dataframe 'dados'
# Parâmetro ---> dicionário
# Chaves ---> rótulos atuais
# Valores ---> rótulos desejados
dados = dados.rename({
    'Date': 'Data',
    'Time': 'Hora',
    'Global_active_power': 'Pot_Ativa',
    'Global_reactive_power': 'Pot_Reativa',
    'Voltage': 'Tensao',
    'Global_intensity': 'Corrente',
    'Sub_metering_1': 'Consumo_1',
    'Sub_metering_2': 'Consumo_2',
    'Sub_metering_3': 'Consumo_3'
}, axis=1)

In [ ]:
dados.columns

Index(['Data', 'Hora', 'Pot_Ativa', 'Pot_Reativa', 'Tensao', 'Corrente',
       'Consumo_1', 'Consumo_2', 'Consumo_3'],
      dtype='object')

In [ ]:
dados.head()

,Data,Hora,Pot_Ativa,Pot_Reativa,Tensao,Corrente,Consumo_1,Consumo_2,Consumo_3
0,2008-12-01 00:00:00,2026-08-07 09:44:00,1.502,0.074,240.17,6.4,0,0,18
1,2006-12-17 00:00:00,2026-08-07 23:39:00,0.374,0.264,245.50,1.8,0,2,0
2,2009-06-03 00:00:00,2026-08-07 17:01:00,0.620,0.300,239.85,3.0,0,1,1
3,2007-05-09 00:00:00,2026-08-07 05:53:00,0.280,0.200,235.72,1.4,0,0,0
4,2008-12-14 00:00:00,2026-08-07 02:57:00,1.372,0.054,243.95,5.6,0,0,18

In [ ]:
# Criar um dataframe 'df1' a partir de 'dados' sem as colunas Data e Hora
# df1 = dados.drop(['Data', 'Hora'], axis=1)
df1 = dados.drop(columns=['Data', 'Hora'])

In [ ]:
df1.head()

   Pot_Ativa  Pot_Reativa  Tensao  Corrente  Consumo_1  Consumo_2  Consumo_3
0      1.502        0.074  240.17       6.4          0          0         18
1      0.374        0.264  245.50       1.8          0          2          0
2      0.620        0.300  239.85       3.0          0          1          1
3      0.280        0.200  235.72       1.4          0          0          0
4      1.372        0.054  243.95       5.6          0          0         18

In [ ]:
# Criar uma variável apenas com os dados da coluna 'Corrente'
# Pandas Series ---> 1 Dimensão
# Pandas DataFrame ---> 2 Dimensões
corrente = dados['Corrente']
corrente

0         6.4
1         1.8
2         3.0
3         1.4
4         5.6
         ...
163938    3.6
163939    6.8
163940    1.2
163941    5.6
163942    1.4
Name: Corrente, Length: 163943, dtype: float64

In [ ]:
type(corrente)

pandas.core.series.Series

In [ ]:
# Criar um dataframe 'df2' a partir de 'dados' somente com as colunas:
# Consumo_3, Corrente, Pot_Ativa, Hora
df2 = dados[['Consumo_3', 'Corrente', 'Pot_Ativa', 'Hora']]
df2.head()

   Consumo_3  Corrente  Pot_Ativa                 Hora
0         18       6.4      1.502  2026-08-07 09:44:00
1          0       1.8      0.374  2026-08-07 23:39:00
2          1       3.0      0.620  2026-08-07 17:01:00
3          0       1.4      0.280  2026-08-07 05:53:00
4         18       5.6      1.372  2026-08-07 02:57:00

In [ ]:
dados.columns

Index(['Data', 'Hora', 'Pot_Ativa', 'Pot_Reativa', 'Tensao', 'Corrente',
       'Consumo_1', 'Consumo_2', 'Consumo_3'],
      dtype='object')

In [ ]:
# Criar um dataframe 'df3' a partir de 'dados' somente com as 4 primeiras colunas
# loc => acesso por rótulos
# iloc => acesso por índices
# : => seleciona rodas as linhas

df3 = dados.iloc[:, 0:4]
df3.head()

                  Data                 Hora  Pot_Ativa  Pot_Reativa
0  2008-12-01 00:00:00  2026-08-07 09:44:00      1.502        0.074
1  2006-12-17 00:00:00  2026-08-07 23:39:00      0.374        0.264
2  2009-06-03 00:00:00  2026-08-07 17:01:00      0.620        0.300
3  2007-05-09 00:00:00  2026-08-07 05:53:00      0.280        0.200
4  2008-12-14 00:00:00  2026-08-07 02:57:00      1.372        0.054

In [ ]:
df3 = dados.loc[:, 'Data':'Consumo_1']
df3.head()

,Data,Hora,Pot_Ativa,Pot_Reativa,Tensao,Corrente,Consumo_1
0,2008-12-01 00:00:00,2026-08-07 09:44:00,1.502,0.074,240.17,6.4,0
1,2006-12-17 00:00:00,2026-08-07 23:39:00,0.374,0.264,245.50,1.8,0
2,2009-06-03 00:00:00,2026-08-07 17:01:00,0.620,0.300,239.85,3.0,0
3,2007-05-09 00:00:00,2026-08-07 05:53:00,0.280,0.200,235.72,1.4,0
4,2008-12-14 00:00:00,2026-08-07 02:57:00,1.372,0.054,243.95,5.6,0

In [ ]:
dados.shape[0]

163943

In [ ]:
# Criar um dataframe 'df4' a partir de dados somente com os registros de consumidores
# cuja demanda energética (Pot_Ativa) está acima de um limiar de 60% de demanda máxima, apenas
# com as colunas Data, Hora, Corrente e Pot_Ativa
df4 = dados[['Data', 'Hora', 'Corrente', 'Pot_Ativa']]
df4.head()

                  Data                 Hora  Corrente  Pot_Ativa
0  2008-12-01 00:00:00  2026-08-07 09:44:00       6.4      1.502
1  2006-12-17 00:00:00  2026-08-07 23:39:00       1.8      0.374
2  2009-06-03 00:00:00  2026-08-07 17:01:00       3.0      0.620
3  2007-05-09 00:00:00  2026-08-07 05:53:00       1.4      0.280
4  2008-12-14 00:00:00  2026-08-07 02:57:00       5.6      1.372

In [ ]:
# Qual é a demanda máxima (PMAX)?
PMAX = dados['Pot_Ativa'].max()

In [ ]:
print(f'A demanda máxima é: {PMAX:.2f} kW')

A demanda máxima é: 10.29 kW

In [ ]:
# Qual é o limiar de 60% da demanda máxima (P60)?
P60 = 0.6 * PMAX
print(f'O limiar de 60% da demanda máxima é: {P60:.2f} kW')

O limiar de 60% da demanda máxima é: 6.17 kW

In [ ]:
df4.columns

Index(['Data', 'Hora', 'Corrente', 'Pot_Ativa'], dtype='object')

In [ ]:
df4 = df4[df4['Pot_Ativa'] > P60]
df4.head()

                     Data                 Hora  Corrente  Pot_Ativa
296   2007-01-20 00:00:00  2026-08-07 19:19:00      27.2      6.240
581   2007-10-13 00:00:00  2026-08-07 20:12:00      30.2      6.888
1488  2008-07-12 00:00:00  2026-08-07 15:44:00      27.2      6.398
2453  2009-12-24 00:00:00  2026-08-07 23:00:00      26.6      6.406
2995  2008-09-04 00:00:00  2026-08-07 20:12:00      30.0      6.838

In [ ]:
print(f'Total de consumidores acima de P60: {df4.shape[0]}')

Total de consumidores acima de P60: 372